using System;
using System.Collections.Generic;

namespace Stock.Services.Models.EF
{
    public partial class Analysis
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public decimal OpenPrice { get; set; }
        public decimal HighPrice { get; set; }
        public decimal LowPrice { get; set; }
        public decimal ClosePrice { get; set; }
        public int Volume { get; set; }
        public DateTime PriceDate { get; set; }
        public decimal? PriceVolume { get; set; }
        public int? Yactual { get; set; }
        public int? Yactual2 { get; set; }
        public int? Yactual3 { get; set; }
        public int? Yactual4 { get; set; }
        public int? Yactual5 { get; set; }
        public int? Yactual6 { get; set; }
        public int? Yactual7 { get; set; }
        public int? Yactual8 { get; set; }
        public int? Yactual9 { get; set; }
        public int? Yactual10 { get; set; }
        public int? Yactual11 { get; set; }
        public int? Yactual12 { get; set; }
        public int? Yactual13 { get; set; }
        public int? Yactual14 { get; set; }
        public int? Yactual15 { get; set; }
        public int? Yactual16 { get; set; }
        public int? Yactual17 { get; set; }
        public int? Yactual18 { get; set; }
        public int? Yactual19 { get; set; }
        public int? Yactual20 { get; set; }
        public int? Yactual21 { get; set; }
        public int? Yactual22 { get; set; }
        public int? Yactual23 { get; set; }
        public int? Yactual24 { get; set; }
        public int? Yactual25 { get; set; }
        public int? Yactual26 { get; set; }
        public int? Yactual27 { get; set; }
        public int? Yactual28 { get; set; }
        public int? Yactual29 { get; set; }
        public int? Yactual30 { get; set; }
        public int? Yactual31 { get; set; }
        public int? Yactual32 { get; set; }
        public int? Yactual33 { get; set; }
        public int? Yactual34 { get; set; }
        public int? Yactual35 { get; set; }
        public int? Yactual36 { get; set; }
        public int? Yactual37 { get; set; }
        public int? Yactual38 { get; set; }
        public int? Yactual39 { get; set; }
        public int? Yactual40 { get; set; }
        public int? Yactual41 { get; set; }
        public int? Yactual42 { get; set; }
        public int? Yactual43 { get; set; }
        public int? Yactual44 { get; set; }
        public int? Yactual45 { get; set; }
        public int? Yactual46 { get; set; }
        public int? Yactual47 { get; set; }
        public int? Yactual48 { get; set; }
        public int? Yactual49 { get; set; }
        public int? Yactual50 { get; set; }
        public int? Yactual51 { get; set; }
        public int? Yactual52 { get; set; }
        public int? Yactual53 { get; set; }
        public int? Yactual54 { get; set; }
        public int? Yactual55 { get; set; }
        public int? Yactual56 { get; set; }
        public int? Yactual57 { get; set; }
        public int? Yactual58 { get; set; }
        public int? Yactual59 { get; set; }
        public int? Yactual60 { get; set; }
        public decimal Sma10 { get; set; }
        public decimal Sma20 { get; set; }
        public decimal Sma50 { get; set; }
        public decimal Sma100 { get; set; }
        public decimal Sma200 { get; set; }
        public bool HasSma10crossAbove20 { get; set; }
        public bool HasSma10crossBelow20 { get; set; }
        public bool HasSma10crossAbove50 { get; set; }
        public bool HasSma10crossBelow50 { get; set; }
        public bool HasSma10crossAbove100 { get; set; }
        public bool HasSma10crossBelow100 { get; set; }
        public bool HasSma10crossAbove200 { get; set; }
        public bool HasSma10crossBelow200 { get; set; }
        public bool HasSma20crossAbove50 { get; set; }
        public bool HasSma20crossBelow50 { get; set; }
        public bool HasSma20crossAbove100 { get; set; }
        public bool HasSma20crossBelow100 { get; set; }
        public bool HasSma20crossAbove200 { get; set; }
        public bool HasSma20crossBelow200 { get; set; }
        public bool HasSma50crossAbove100 { get; set; }
        public bool HasSma50crossBelow100 { get; set; }
        public bool HasSma50crossAbove200 { get; set; }
        public bool HasSma50crossBelow200 { get; set; }
        public bool HasSma100crossAbove200 { get; set; }
        public bool HasSma100crossBelow200 { get; set; }
        public decimal Ema5 { get; set; }
        public decimal Ema9 { get; set; }
        public decimal Ema10 { get; set; }
        public decimal Ema12 { get; set; }
        public decimal Ema13 { get; set; }
        public decimal Ema26 { get; set; }
        public decimal Ema48 { get; set; }
        public bool HasEma5crossAbove9 { get; set; }
        public bool HasEma5crossBelow9 { get; set; }
        public bool HasEma5crossAbove10 { get; set; }
        public bool HasEma5crossBelow10 { get; set; }
        public bool HasEma5crossAbove12 { get; set; }
        public bool HasEma5crossBelow12 { get; set; }
        public bool HasEma5crossAbove13 { get; set; }
        public bool HasEma5crossBelow13 { get; set; }
        public bool HasEma5crossAbove26 { get; set; }
        public bool HasEma5crossBelow26 { get; set; }
        public bool HasEma5crossAbove48 { get; set; }
        public bool HasEma5crossBelow48 { get; set; }
        public bool HasEma9crossAbove10 { get; set; }
        public bool HasEma9crossBelow10 { get; set; }
        public bool HasEma9crossAbove12 { get; set; }
        public bool HasEma9crossBelow12 { get; set; }
        public bool HasEma9crossAbove13 { get; set; }
        public bool HasEma9crossBelow13 { get; set; }
        public bool HasEma9crossAbove26 { get; set; }
        public bool HasEma9crossBelow26 { get; set; }
        public bool HasEma9crossAbove48 { get; set; }
        public bool HasEma9crossBelow48 { get; set; }
        public bool HasEma10crossAbove12 { get; set; }
        public bool HasEma10crossBelow12 { get; set; }
        public bool HasEma10crossAbove13 { get; set; }
        public bool HasEma10crossBelow13 { get; set; }
        public bool HasEma10crossAbove26 { get; set; }
        public bool HasEma10crossBelow26 { get; set; }
        public bool HasEma10crossAbove48 { get; set; }
        public bool HasEma10crossBelow48 { get; set; }
        public bool HasEma12crossAbove13 { get; set; }
        public bool HasEma12crossBelow13 { get; set; }
        public bool HasEma12crossAbove26 { get; set; }
        public bool HasEma12crossBelow26 { get; set; }
        public bool HasEma12crossAbove48 { get; set; }
        public bool HasEma12crossBelow48 { get; set; }
        public bool HasEma13crossAbove26 { get; set; }
        public bool HasEma13crossBelow26 { get; set; }
        public bool HasEma13crossAbove48 { get; set; }
        public bool HasEma13crossBelow48 { get; set; }
        public bool HasEma26crossAbove48 { get; set; }
        public bool HasEma26crossBelow48 { get; set; }
        public decimal Adtv20 { get; set; }
        public decimal Adtv30 { get; set; }
        public decimal Adtv50 { get; set; }
        public decimal Adpv20 { get; set; }
        public decimal Adpv30 { get; set; }
        public decimal Adpv50 { get; set; }
        public decimal Rsi6 { get; set; }
        public decimal Rsi10 { get; set; }
        public decimal Rsi14 { get; set; }
        public decimal? AvgGain6 { get; set; }
        public decimal? AvgLoss6 { get; set; }
        public decimal? AvgGain10 { get; set; }
        public decimal? AvgLoss10 { get; set; }
        public decimal? AvgGain14 { get; set; }
        public decimal? AvgLoss14 { get; set; }
        public bool HasRsi6crossAbove70 { get; set; }
        public bool HasRsi6crossAbove75 { get; set; }
        public bool HasRsi6crossAbove80 { get; set; }
        public bool HasRsi6crossAbove85 { get; set; }
        public bool HasRsi6crossBelow30 { get; set; }
        public bool HasRsi6crossBelow25 { get; set; }
        public bool HasRsi6crossBelow20 { get; set; }
        public bool HasRsi6crossBelow15 { get; set; }
        public bool HasRsi10crossAbove70 { get; set; }
        public bool HasRsi10crossAbove75 { get; set; }
        public bool HasRsi10crossAbove80 { get; set; }
        public bool HasRsi10crossAbove85 { get; set; }
        public bool HasRsi10crossBelow30 { get; set; }
        public bool HasRsi10crossBelow25 { get; set; }
        public bool HasRsi10crossBelow20 { get; set; }
        public bool HasRsi10crossBelow15 { get; set; }
        public bool HasRsi14crossAbove70 { get; set; }
        public bool HasRsi14crossAbove75 { get; set; }
        public bool HasRsi14crossAbove80 { get; set; }
        public bool HasRsi14crossAbove85 { get; set; }
        public bool HasRsi14crossBelow30 { get; set; }
        public bool HasRsi14crossBelow25 { get; set; }
        public bool HasRsi14crossBelow20 { get; set; }
        public bool HasRsi14crossBelow15 { get; set; }
        public bool IsLocalMax10 { get; set; }
        public bool IsLocalMax20 { get; set; }
        public bool IsLocalMax50 { get; set; }
        public bool IsLocalMax200 { get; set; }
        public bool IsLocalMin10 { get; set; }
        public bool IsLocalMin20 { get; set; }
        public bool IsLocalMin50 { get; set; }
        public bool IsLocalMin200 { get; set; }
        public decimal BollingerUpperStvDev120 { get; set; }
        public decimal BollingerLowerStvDev120 { get; set; }
        public decimal BollingerUpperStvDev220 { get; set; }
        public decimal BollingerLowerStvDev220 { get; set; }
        public decimal BollingerUpperStvDev2520 { get; set; }
        public decimal BollingerLowerStvDev2520 { get; set; }
        public bool HasCrossAboveBollingerUpperStvDev220 { get; set; }
        public bool HasCrossBelowBollingerLowerStvDev220 { get; set; }
        public bool HasCrossAboveBollingerUpperStvDev2520 { get; set; }
        public bool HasCrossBelowBollingerLowerStvDev2520 { get; set; }
    }
}
